version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: postgres_con
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_LOCAL: ${POSTGRES_HOST}
    volumes:
      - db_data:/var/lib/postgresql/data_25_10_23
      
  app:
    build: .
    image: node
    container_name: node_on_postgres_con
    restart: unless-stopped
    volumes:
      - ./dist/data:/app/dist/data
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env.prod
volumes:
  db_data: